# Generated by Django 4.0.4 on 2022-04-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contactsmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contactsmodel',
            name='reason',
            field=models.CharField(choices=[('Request Invoice for order', 'Request Invoice for order'), ('Request order status', 'Request order status'), ("Haven't received cashback yet", "Haven't received cashback yet"), ('Other', 'Other')], default='--Select Your Issue--', max_length=100),
        ),
    ]
