# Generated by Django 4.0.4 on 2022-04-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contactsmodel_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsmodel',
            name='subject',
        ),
    ]
