# Generated by Django 4.0.4 on 2022-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contactsmodel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='reason',
            field=models.CharField(choices=[('--Select Your Issue--', '--Select Your Issue--'), ('Request invoice for order', 'Request invoice for order'), ('Request refund for order', 'Request refund for order'), ('Request order status', 'Request order status'), ("Haven't received cashback yet", "Haven't received cashback yet"), ('Other', 'Other')], default='--Select Your Issue--', max_length=100),
        ),
    ]
