# Generated by Django 4.0.4 on 2022-06-05 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_billingaddress_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='zip_code',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(99950)),
        ),
    ]
