# Generated by Django 4.0.4 on 2022-06-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_refund_requested_order_refunded'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('Standard delivery - 4.95', 'Standard delivery - 4.95'), ('Express delivery - 8.95', 'Express delivery - 8.95')], default='Choose type of delivery', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.deliveryservice'),
        ),
    ]
