# Generated by Django 4.0.4 on 2022-06-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_deliveryservice_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryservice',
            name='delivery',
            field=models.CharField(choices=[('Standard delivery - 4.95', 'Standard delivery - 4.95'), ('Express delivery - 8.95', 'Express delivery - 8.95')], default='Standard delivery - 4.95', max_length=100),
        ),
    ]
