# Generated by Django 4.0.4 on 2022-06-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_deliveryservice_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryService',
        ),
    ]
