# Generated by Django 4.0.4 on 2022-04-27 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=40)),
                ('large_description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('image_url', models.ImageField(upload_to='blog/')),
            ],
        ),
    ]
