# Generated by Django 4.0.4 on 2022-05-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='email',
        ),
    ]
