# Generated by Django 4.0.4 on 2022-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_comment_email_remove_reply_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, default='asd@abv.bg', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='email',
            field=models.EmailField(blank=True, default='asd@abv.bg', max_length=254, null=True),
        ),
    ]
