# Generated by Django 4.0.4 on 2022-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_comment_email_reply_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reply',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
